### PR TITLE
Revert "Update module file for 1.13"

### PR DESCRIPTION
**Pull request by jdolitsky**
Reverts deislabs/oras#132

### CODE REVIEW

**Comment by jdolitsky** [comment]
some error on CI:

```
# github.com/docker/cli/cli/config                                                                                             
/go/pkg/mod/github.com/docker/cli@v0.0.0-20191007193719-3e07fa728a30/cli/config/config.go:30:19: undefined: os.UserHomeDir     
/go/pkg/mod/github.com/docker/cli@v0.0.0-20191007193719-3e07fa728a30/cli/config/config.go:111:18: undefined: os.UserHomeDir    
# github.com/docker/distribution/registry                                                                                      
/go/pkg/mod/github.com/docker/distribution@v2.7.1+incompatible/registry/registry.go:157:10: undefined: letsencrypt.Manager     
FAIL    github.com/deislabs/oras/pkg/auth/docker [build failed] 
```

reverting #132 until we can fix 

cc @jpreese

**Comment by jpreese** [comment]
This is most likely due to the `yml` in the `.codefresh/` dir that reference `golang-1.11`. The module resolution algorithm changes quite a bit from 1.11 to 1.12, and some more from 1.12 to 1.13.

Is there a way I can update the golang version that the pr/release use and test it locally? Definitely value in getting those wired up, unless I've missed it.
